"""initial schema

Revision ID: 0001
Revises: 
Create Date: 2026-03-17 20:56:19.748967

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0001'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_runtime_audits',
    sa.Column('actor', sa.String(length=255), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('changed_fields', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_runtime_audits_created_at'), 'ai_runtime_audits', ['created_at'], unique=False)
    op.create_index(op.f('ix_ai_runtime_audits_deleted_at'), 'ai_runtime_audits', ['deleted_at'], unique=False)
    op.create_table('ai_runtime_secrets',
    sa.Column('bearer_token_encrypted', sa.Text(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_runtime_secrets_created_at'), 'ai_runtime_secrets', ['created_at'], unique=False)
    op.create_index(op.f('ix_ai_runtime_secrets_deleted_at'), 'ai_runtime_secrets', ['deleted_at'], unique=False)
    op.create_table('ai_runtime_settings',
    sa.Column('model', sa.String(length=120), nullable=False),
    sa.Column('ai_base_url', sa.Text(), nullable=False),
    sa.Column('ai_provider_mode', sa.String(length=40), nullable=False),
    sa.Column('system_prompt', sa.Text(), nullable=False),
    sa.Column('temperature', sa.Float(), nullable=False),
    sa.Column('max_tokens_per_request', sa.Integer(), nullable=False),
    sa.Column('strict_actions', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("ai_provider_mode IN ('openai_compatible', 'timeweb_native')", name='ck_ai_runtime_settings_provider_mode'),
    sa.CheckConstraint('max_tokens_per_request >= 64', name='ck_ai_runtime_settings_max_tokens_min'),
    sa.CheckConstraint('temperature >= 0 AND temperature <= 2', name='ck_ai_runtime_settings_temperature_range'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_runtime_settings_created_at'), 'ai_runtime_settings', ['created_at'], unique=False)
    op.create_index(op.f('ix_ai_runtime_settings_deleted_at'), 'ai_runtime_settings', ['deleted_at'], unique=False)
    op.create_table('billing_runtime_audits',
    sa.Column('actor', sa.String(length=255), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('changed_fields', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_billing_runtime_audits_created_at'), 'billing_runtime_audits', ['created_at'], unique=False)
    op.create_index(op.f('ix_billing_runtime_audits_deleted_at'), 'billing_runtime_audits', ['deleted_at'], unique=False)
    op.create_table('billing_runtime_secrets',
    sa.Column('yookassa_secret_key_encrypted', sa.Text(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_billing_runtime_secrets_created_at'), 'billing_runtime_secrets', ['created_at'], unique=False)
    op.create_index(op.f('ix_billing_runtime_secrets_deleted_at'), 'billing_runtime_secrets', ['deleted_at'], unique=False)
    op.create_table('billing_runtime_settings',
    sa.Column('yookassa_shop_id', sa.String(length=255), nullable=False),
    sa.Column('yookassa_return_url', sa.Text(), nullable=False),
    sa.Column('yookassa_webhook_url', sa.Text(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_billing_runtime_settings_created_at'), 'billing_runtime_settings', ['created_at'], unique=False)
    op.create_index(op.f('ix_billing_runtime_settings_deleted_at'), 'billing_runtime_settings', ['deleted_at'], unique=False)
    op.create_table('organizations',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('plan', sa.Enum('free', 'team', 'business', name='plantier'), server_default=sa.text("'free'"), nullable=False),
    sa.Column('ai_enabled', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_organizations_created_at'), 'organizations', ['created_at'], unique=False)
    op.create_index(op.f('ix_organizations_deleted_at'), 'organizations', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_organizations_slug'), 'organizations', ['slug'], unique=True)
    op.create_table('plans',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('price_monthly', sa.Integer(), nullable=False),
    sa.Column('price_yearly', sa.Integer(), nullable=False),
    sa.Column('max_members', sa.Integer(), nullable=False),
    sa.Column('max_tables', sa.Integer(), nullable=False),
    sa.Column('max_records', sa.Integer(), nullable=False),
    sa.Column('max_storage_mb', sa.Integer(), nullable=False),
    sa.Column('has_ai', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('ai_max_tokens_per_request', sa.Integer(), nullable=False),
    sa.Column('ai_tokens_per_day', sa.Integer(), nullable=False),
    sa.Column('ai_rpm_per_user', sa.Integer(), nullable=False),
    sa.Column('features', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_plans_created_at'), 'plans', ['created_at'], unique=False)
    op.create_index(op.f('ix_plans_deleted_at'), 'plans', ['deleted_at'], unique=False)
    op.create_table('superadmin_runtime_audits',
    sa.Column('actor', sa.String(length=255), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('changed_fields', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_superadmin_runtime_audits_created_at'), 'superadmin_runtime_audits', ['created_at'], unique=False)
    op.create_index(op.f('ix_superadmin_runtime_audits_deleted_at'), 'superadmin_runtime_audits', ['deleted_at'], unique=False)
    op.create_table('superadmin_runtime_secrets',
    sa.Column('password_hash', sa.Text(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_superadmin_runtime_secrets_created_at'), 'superadmin_runtime_secrets', ['created_at'], unique=False)
    op.create_index(op.f('ix_superadmin_runtime_secrets_deleted_at'), 'superadmin_runtime_secrets', ['deleted_at'], unique=False)
    op.create_table('superadmin_runtime_settings',
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_superadmin_runtime_settings_created_at'), 'superadmin_runtime_settings', ['created_at'], unique=False)
    op.create_index(op.f('ix_superadmin_runtime_settings_deleted_at'), 'superadmin_runtime_settings', ['deleted_at'], unique=False)
    op.create_table('token_packages',
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('badge_text', sa.String(length=120), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('button_text', sa.String(length=120), nullable=True),
    sa.Column('payment_note', sa.Text(), nullable=True),
    sa.Column('price_caption', sa.String(length=255), nullable=True),
    sa.Column('tokens', sa.Integer(), nullable=False),
    sa.Column('price_rub_cents', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('sort_order', sa.Integer(), server_default=sa.text('100'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('price_rub_cents >= 0', name='ck_token_packages_price_non_negative'),
    sa.CheckConstraint('tokens > 0', name='ck_token_packages_tokens_positive'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code', name='uq_token_packages_code')
    )
    op.create_index(op.f('ix_token_packages_code'), 'token_packages', ['code'], unique=False)
    op.create_index(op.f('ix_token_packages_created_at'), 'token_packages', ['created_at'], unique=False)
    op.create_index(op.f('ix_token_packages_deleted_at'), 'token_packages', ['deleted_at'], unique=False)
    op.create_table('users',
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('hashed_password', sa.String(length=1024), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('timezone', sa.String(length=50), server_default=sa.text("'UTC'"), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_created_at'), 'users', ['created_at'], unique=False)
    op.create_index(op.f('ix_users_deleted_at'), 'users', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('access_rules',
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('resource_type', sa.String(length=50), nullable=False),
    sa.Column('resource_id', sa.UUID(), nullable=True),
    sa.Column('role', sa.String(length=50), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('can_read', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('can_write', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('can_delete', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("resource_type IN ('table', 'knowledge', 'ai', 'schedule', 'reports', 'files')", name='ck_access_rules_resource_type_valid'),
    sa.CheckConstraint("role IS NULL OR role IN ('owner', 'admin', 'manager', 'employee', 'readonly')", name='ck_access_rules_role_valid'),
    sa.CheckConstraint('(role IS NULL) <> (user_id IS NULL)', name='ck_access_rules_role_xor_user'),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_access_rules_created_at'), 'access_rules', ['created_at'], unique=False)
    op.create_index(op.f('ix_access_rules_deleted_at'), 'access_rules', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_access_rules_org_id'), 'access_rules', ['org_id'], unique=False)
    op.create_index(op.f('ix_access_rules_resource_id'), 'access_rules', ['resource_id'], unique=False)
    op.create_index(op.f('ix_access_rules_resource_type'), 'access_rules', ['resource_type'], unique=False)
    op.create_index(op.f('ix_access_rules_user_id'), 'access_rules', ['user_id'], unique=False)
    op.create_table('ai_chat_sessions',
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id', 'org_id', 'user_id', name='uq_ai_chat_sessions_id_org_user')
    )
    op.create_index(op.f('ix_ai_chat_sessions_created_at'), 'ai_chat_sessions', ['created_at'], unique=False)
    op.create_index(op.f('ix_ai_chat_sessions_deleted_at'), 'ai_chat_sessions', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_ai_chat_sessions_org_id'), 'ai_chat_sessions', ['org_id'], unique=False)
    op.create_index(op.f('ix_ai_chat_sessions_user_id'), 'ai_chat_sessions', ['user_id'], unique=False)
    op.create_table('ai_org_limits',
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('daily_tokens_limit', sa.Integer(), nullable=False),
    sa.Column('monthly_tokens_limit', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('daily_tokens_limit >= 0', name='ck_ai_org_limits_daily_non_negative'),
    sa.CheckConstraint('monthly_tokens_limit >= 0', name='ck_ai_org_limits_monthly_non_negative'),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('org_id', name='uq_ai_org_limits_org_id')
    )
    op.create_index(op.f('ix_ai_org_limits_created_at'), 'ai_org_limits', ['created_at'], unique=False)
    op.create_index(op.f('ix_ai_org_limits_deleted_at'), 'ai_org_limits', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_ai_org_limits_org_id'), 'ai_org_limits', ['org_id'], unique=False)
    op.create_table('ai_usage_logs',
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('model', sa.String(length=100), nullable=False),
    sa.Column('prompt_tokens', sa.Integer(), nullable=False),
    sa.Column('completion_tokens', sa.Integer(), nullable=False),
    sa.Column('total_tokens', sa.Integer(), nullable=False),
    sa.Column('message_preview', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('completion_tokens >= 0', name='ck_ai_usage_logs_completion_tokens_non_negative'),
    sa.CheckConstraint('prompt_tokens >= 0', name='ck_ai_usage_logs_prompt_tokens_non_negative'),
    sa.CheckConstraint('total_tokens >= 0', name='ck_ai_usage_logs_total_tokens_non_negative'),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_usage_logs_created_at'), 'ai_usage_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_ai_usage_logs_deleted_at'), 'ai_usage_logs', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_ai_usage_logs_org_id'), 'ai_usage_logs', ['org_id'], unique=False)
    op.create_index(op.f('ix_ai_usage_logs_user_id'), 'ai_usage_logs', ['user_id'], unique=False)
    op.create_table('ai_user_limits',
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('daily_tokens_limit', sa.Integer(), nullable=False),
    sa.Column('rpm_limit', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('daily_tokens_limit >= 0', name='ck_ai_user_limits_daily_non_negative'),
    sa.CheckConstraint('rpm_limit >= 0', name='ck_ai_user_limits_rpm_non_negative'),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('org_id', 'user_id', name='uq_ai_user_limits_org_user')
    )
    op.create_index(op.f('ix_ai_user_limits_created_at'), 'ai_user_limits', ['created_at'], unique=False)
    op.create_index(op.f('ix_ai_user_limits_deleted_at'), 'ai_user_limits', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_ai_user_limits_org_id'), 'ai_user_limits', ['org_id'], unique=False)
    op.create_index(op.f('ix_ai_user_limits_user_id'), 'ai_user_limits', ['user_id'], unique=False)
    op.create_table('audit_logs',
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('actor_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.Enum('create', 'update', 'delete', 'login', 'logout', 'invite_sent', 'invite_accepted', 'role_changed', 'export', 'ai_query', 'login_failed', 'access_denied', 'token_anomaly', name='auditaction'), nullable=False),
    sa.Column('entity_type', sa.String(length=100), nullable=False),
    sa.Column('entity_id', sa.String(length=100), nullable=True),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('correlation_id', sa.String(length=64), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_correlation_id'), 'audit_logs', ['correlation_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_created_at'), 'audit_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_audit_logs_deleted_at'), 'audit_logs', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_audit_logs_org_id'), 'audit_logs', ['org_id'], unique=False)
    op.create_table('events',
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('assigned_to', sa.UUID(), nullable=True),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('start_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('all_day', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('color', sa.String(length=20), nullable=True),
    sa.Column('is_done', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('recurrence', sa.Text(), nullable=True),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['assigned_to'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_events_created_at'), 'events', ['created_at'], unique=False)
    op.create_index(op.f('ix_events_deleted_at'), 'events', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_events_org_id'), 'events', ['org_id'], unique=False)
    op.create_table('folders',
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('parent_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('position', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_id'], ['folders.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_folders_created_at'), 'folders', ['created_at'], unique=False)
    op.create_index(op.f('ix_folders_created_by'), 'folders', ['created_by'], unique=False)
    op.create_index(op.f('ix_folders_deleted_at'), 'folders', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_folders_org_id'), 'folders', ['org_id'], unique=False)
    op.create_index(op.f('ix_folders_parent_id'), 'folders', ['parent_id'], unique=False)
    op.create_table('files',
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('uploaded_by', sa.UUID(), nullable=True),
    sa.Column('filename', sa.String(length=500), nullable=False),
    sa.Column('original_name', sa.String(length=500), nullable=False),
    sa.Column('content_type', sa.String(length=255), nullable=False),
    sa.Column('size', sa.BigInteger(), nullable=False),
    sa.Column('s3_key', sa.String(length=1000), nullable=False),
    sa.Column('s3_bucket', sa.String(length=255), nullable=False),
    sa.Column('folder_id', sa.UUID(), nullable=True),
    sa.Column('type', sa.String(length=20), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=True),
    sa.Column('title', sa.String(length=500), nullable=True),
    sa.Column('current_version_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['folder_id'], ['folders.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('s3_key')
    )
    op.create_index(op.f('ix_files_created_at'), 'files', ['created_at'], unique=False)
    op.create_index(op.f('ix_files_current_version_id'), 'files', ['current_version_id'], unique=False)
    op.create_index(op.f('ix_files_deleted_at'), 'files', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_files_folder_id'), 'files', ['folder_id'], unique=False)
    op.create_index(op.f('ix_files_org_id'), 'files', ['org_id'], unique=False)
    op.create_index(op.f('ix_files_status'), 'files', ['status'], unique=False)
    op.create_index(op.f('ix_files_type'), 'files', ['type'], unique=False)
    op.create_table('file_versions',
    sa.Column('file_id', sa.UUID(), nullable=False),
    sa.Column('s3_key', sa.String(length=1000), nullable=False),
    sa.Column('s3_bucket', sa.String(length=255), nullable=False),
    sa.Column('size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('sha256', sa.String(length=128), nullable=True),
    sa.Column('mime', sa.String(length=255), nullable=False),
    sa.Column('meta_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['file_id'], ['files.id'], name='fk_file_versions_file_id', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('s3_key')
    )
    op.create_index(op.f('ix_file_versions_created_at'), 'file_versions', ['created_at'], unique=False)
    op.create_index(op.f('ix_file_versions_created_by'), 'file_versions', ['created_by'], unique=False)
    op.create_index(op.f('ix_file_versions_deleted_at'), 'file_versions', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_file_versions_file_id'), 'file_versions', ['file_id'], unique=False)
    op.create_foreign_key(
        'fk_files_current_version_id',
        'files',
        'file_versions',
        ['current_version_id'],
        ['id'],
        ondelete='SET NULL',
    )
    op.execute(
        """
        CREATE OR REPLACE FUNCTION crm_enforce_folders_depth()
        RETURNS trigger AS $$
        DECLARE
            v_cursor_id uuid;
            v_cursor_parent_id uuid;
            v_cursor_org_id uuid;
            v_depth integer := 0;
        BEGIN
            IF NEW.parent_id IS NULL THEN
                RETURN NEW;
            END IF;

            IF NEW.parent_id = NEW.id THEN
                RAISE EXCEPTION 'INVALID_PARENT_SELF';
            END IF;

            v_cursor_id := NEW.parent_id;

            LOOP
                SELECT parent_id, org_id
                  INTO v_cursor_parent_id, v_cursor_org_id
                  FROM folders
                 WHERE id = v_cursor_id;

                IF v_cursor_org_id IS NULL THEN
                    RAISE EXCEPTION 'PARENT_FOLDER_NOT_FOUND';
                END IF;

                IF v_cursor_org_id <> NEW.org_id THEN
                    RAISE EXCEPTION 'PARENT_FOLDER_ORG_MISMATCH';
                END IF;

                v_depth := v_depth + 1;
                IF v_depth > 2 THEN
                    RAISE EXCEPTION 'MAX_DEPTH_EXCEEDED';
                END IF;

                EXIT WHEN v_cursor_parent_id IS NULL;
                v_cursor_id := v_cursor_parent_id;
            END LOOP;

            RETURN NEW;
        END;
        $$ LANGUAGE plpgsql;
        """
    )
    op.execute(
        """
        CREATE TRIGGER trg_folders_depth_insert
        BEFORE INSERT ON folders
        FOR EACH ROW
        EXECUTE FUNCTION crm_enforce_folders_depth();
        """
    )
    op.execute(
        """
        CREATE TRIGGER trg_folders_depth_update
        BEFORE UPDATE OF parent_id, org_id ON folders
        FOR EACH ROW
        EXECUTE FUNCTION crm_enforce_folders_depth();
        """
    )
    op.create_table('docs_ai_generation_jobs',
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('file_id', sa.UUID(), nullable=True),
    sa.Column('file_type', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=32), server_default=sa.text("'queued'"), nullable=False),
    sa.Column('prompt', sa.Text(), nullable=False),
    sa.Column('template', sa.String(length=120), nullable=True),
    sa.Column('title', sa.String(length=500), nullable=True),
    sa.Column('language', sa.String(length=16), nullable=True),
    sa.Column('provider_model', sa.String(length=120), nullable=True),
    sa.Column('prompt_tokens', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('completion_tokens', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('total_tokens', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('task_id', sa.String(length=120), nullable=True),
    sa.Column('meta_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("status IN ('queued','running','scanning','ready','blocked','failed')", name='ck_docs_ai_generation_jobs_status'),
    sa.CheckConstraint('completion_tokens >= 0', name='ck_docs_ai_generation_jobs_completion_non_negative'),
    sa.CheckConstraint('prompt_tokens >= 0', name='ck_docs_ai_generation_jobs_prompt_non_negative'),
    sa.CheckConstraint('total_tokens >= 0', name='ck_docs_ai_generation_jobs_total_non_negative'),
    sa.ForeignKeyConstraint(['file_id'], ['files.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_docs_ai_generation_jobs_created_at'), 'docs_ai_generation_jobs', ['created_at'], unique=False)
    op.create_index(op.f('ix_docs_ai_generation_jobs_deleted_at'), 'docs_ai_generation_jobs', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_docs_ai_generation_jobs_file_id'), 'docs_ai_generation_jobs', ['file_id'], unique=False)
    op.create_index(op.f('ix_docs_ai_generation_jobs_org_id'), 'docs_ai_generation_jobs', ['org_id'], unique=False)
    op.create_index(op.f('ix_docs_ai_generation_jobs_user_id'), 'docs_ai_generation_jobs', ['user_id'], unique=False)
    op.create_table('invites',
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('role', sa.Enum('superadmin', 'owner', 'admin', 'manager', 'employee', 'readonly', name='userrole'), nullable=False),
    sa.Column('status', sa.Enum('pending', 'accepted', 'expired', 'cancelled', name='invitestatus'), server_default=sa.text("'pending'"), nullable=False),
    sa.Column('token', sa.String(length=512), nullable=False),
    sa.Column('invited_by', sa.UUID(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['invited_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    op.create_index(op.f('ix_invites_created_at'), 'invites', ['created_at'], unique=False)
    op.create_index(op.f('ix_invites_deleted_at'), 'invites', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_invites_email'), 'invites', ['email'], unique=False)
    op.create_index(op.f('ix_invites_org_id'), 'invites', ['org_id'], unique=False)
    op.create_table('kb_pages',
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('parent_id', sa.UUID(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('slug', sa.String(length=500), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('icon', sa.String(length=50), nullable=True),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('is_published', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_id'], ['kb_pages.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_kb_pages_created_at'), 'kb_pages', ['created_at'], unique=False)
    op.create_index(op.f('ix_kb_pages_deleted_at'), 'kb_pages', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_kb_pages_org_id'), 'kb_pages', ['org_id'], unique=False)
    op.create_index(op.f('ix_kb_pages_parent_id'), 'kb_pages', ['parent_id'], unique=False)
    op.create_table('memberships',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.Enum('superadmin', 'owner', 'admin', 'manager', 'employee', 'readonly', name='userrole'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    comment='User membership in an organization with role'
    )
    op.create_index(op.f('ix_memberships_created_at'), 'memberships', ['created_at'], unique=False)
    op.create_index(op.f('ix_memberships_deleted_at'), 'memberships', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_memberships_org_id'), 'memberships', ['org_id'], unique=False)
    op.create_index(op.f('ix_memberships_user_id'), 'memberships', ['user_id'], unique=False)
    op.create_table('notifications',
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.Enum('in_app', 'email', name='notificationtype'), nullable=False),
    sa.Column('status', sa.Enum('pending', 'sent', 'read', 'failed', name='notificationstatus'), server_default=sa.text("'pending'"), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_read', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_created_at'), 'notifications', ['created_at'], unique=False)
    op.create_index(op.f('ix_notifications_deleted_at'), 'notifications', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_notifications_org_id'), 'notifications', ['org_id'], unique=False)
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.create_table('org_storage_usage',
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('used_bytes', sa.BigInteger(), server_default=sa.text('0'), nullable=False),
    sa.Column('reserved_bytes', sa.BigInteger(), server_default=sa.text('0'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('reserved_bytes >= 0', name='ck_org_storage_usage_reserved_non_negative'),
    sa.CheckConstraint('used_bytes >= 0', name='ck_org_storage_usage_used_non_negative'),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_org_storage_usage_created_at'), 'org_storage_usage', ['created_at'], unique=False)
    op.create_index(op.f('ix_org_storage_usage_deleted_at'), 'org_storage_usage', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_org_storage_usage_org_id'), 'org_storage_usage', ['org_id'], unique=True)
    op.create_table('refresh_tokens',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('token_hash', sa.String(length=512), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_revoked', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('user_agent', sa.String(length=512), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )
    op.create_index(op.f('ix_refresh_tokens_created_at'), 'refresh_tokens', ['created_at'], unique=False)
    op.create_index(op.f('ix_refresh_tokens_deleted_at'), 'refresh_tokens', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_refresh_tokens_user_id'), 'refresh_tokens', ['user_id'], unique=False)
    op.create_table('report_dashboards',
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_report_dashboards_created_at'), 'report_dashboards', ['created_at'], unique=False)
    op.create_index(op.f('ix_report_dashboards_deleted_at'), 'report_dashboards', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_report_dashboards_org_id'), 'report_dashboards', ['org_id'], unique=False)
    op.create_table('subscriptions',
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('plan', sa.Enum('free', 'team', 'business', name='plantier'), nullable=False),
    sa.Column('status', sa.Enum('active', 'past_due', 'cancelled', 'trialing', name='subscriptionstatus'), nullable=False),
    sa.Column('current_period_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('current_period_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('grace_period_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('data_purge_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('pre_expiry_notified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('post_expiry_notified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('downgraded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('data_purged_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('external_id', sa.String(length=255), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('org_id')
    )
    op.create_index(op.f('ix_subscriptions_created_at'), 'subscriptions', ['created_at'], unique=False)
    op.create_index(op.f('ix_subscriptions_deleted_at'), 'subscriptions', ['deleted_at'], unique=False)
    op.create_table('table_folders',
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('parent_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('position', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_id'], ['table_folders.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_table_folders_created_at'), 'table_folders', ['created_at'], unique=False)
    op.create_index(op.f('ix_table_folders_deleted_at'), 'table_folders', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_table_folders_org_id'), 'table_folders', ['org_id'], unique=False)
    op.create_index(op.f('ix_table_folders_parent_id'), 'table_folders', ['parent_id'], unique=False)
    op.create_table('token_balances',
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('plan_cycle_key', sa.String(length=7), nullable=False),
    sa.Column('plan_tokens_monthly_quota', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('plan_tokens_remaining', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('addon_tokens_remaining', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('addon_tokens_remaining >= 0', name='ck_token_balances_addon_non_negative'),
    sa.CheckConstraint('plan_tokens_monthly_quota >= 0', name='ck_token_balances_plan_quota_non_negative'),
    sa.CheckConstraint('plan_tokens_remaining >= 0', name='ck_token_balances_plan_non_negative'),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('org_id', name='uq_token_balances_org_id')
    )
    op.create_index(op.f('ix_token_balances_created_at'), 'token_balances', ['created_at'], unique=False)
    op.create_index(op.f('ix_token_balances_deleted_at'), 'token_balances', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_token_balances_org_id'), 'token_balances', ['org_id'], unique=False)
    op.create_table('token_ledger',
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('operation', sa.String(length=64), nullable=False),
    sa.Column('delta_tokens', sa.Integer(), nullable=False),
    sa.Column('plan_delta_tokens', sa.Integer(), nullable=True),
    sa.Column('addon_delta_tokens', sa.Integer(), nullable=True),
    sa.Column('request_id', sa.String(length=128), nullable=True),
    sa.Column('balance_plan_after', sa.Integer(), nullable=True),
    sa.Column('balance_addon_after', sa.Integer(), nullable=True),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('addon_delta_tokens IS NULL OR addon_delta_tokens != 0', name='ck_token_ledger_addon_delta_non_zero'),
    sa.CheckConstraint('delta_tokens != 0', name='ck_token_ledger_delta_non_zero'),
    sa.CheckConstraint('plan_delta_tokens IS NULL OR plan_delta_tokens != 0', name='ck_token_ledger_plan_delta_non_zero'),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_token_ledger_created_at'), 'token_ledger', ['created_at'], unique=False)
    op.create_index(op.f('ix_token_ledger_deleted_at'), 'token_ledger', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_token_ledger_operation'), 'token_ledger', ['operation'], unique=False)
    op.create_index(op.f('ix_token_ledger_org_id'), 'token_ledger', ['org_id'], unique=False)
    op.create_index(op.f('ix_token_ledger_request_id'), 'token_ledger', ['request_id'], unique=False)
    op.create_index(op.f('ix_token_ledger_user_id'), 'token_ledger', ['user_id'], unique=False)
    op.create_table('token_purchases',
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('package_code', sa.String(length=64), nullable=False),
    sa.Column('tokens_total', sa.Integer(), nullable=False),
    sa.Column('tokens_remaining', sa.Integer(), nullable=False),
    sa.Column('payment_id', sa.String(length=255), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('tokens_remaining <= tokens_total', name='ck_token_purchases_tokens_remaining_le_total'),
    sa.CheckConstraint('tokens_remaining >= 0', name='ck_token_purchases_tokens_remaining_non_negative'),
    sa.CheckConstraint('tokens_total > 0', name='ck_token_purchases_tokens_total_positive'),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_token_purchases_created_at'), 'token_purchases', ['created_at'], unique=False)
    op.create_index(op.f('ix_token_purchases_deleted_at'), 'token_purchases', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_token_purchases_expires_at'), 'token_purchases', ['expires_at'], unique=False)
    op.create_index(op.f('ix_token_purchases_org_id'), 'token_purchases', ['org_id'], unique=False)
    op.create_index(op.f('ix_token_purchases_payment_id'), 'token_purchases', ['payment_id'], unique=False)
    op.create_table('token_usage_idempotency',
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('request_id', sa.String(length=128), nullable=False),
    sa.Column('spent_total', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('spent_addon', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('spent_plan', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('spent_addon >= 0', name='ck_token_usage_idem_spent_addon_non_negative'),
    sa.CheckConstraint('spent_plan >= 0', name='ck_token_usage_idem_spent_plan_non_negative'),
    sa.CheckConstraint('spent_total >= 0', name='ck_token_usage_idem_spent_non_negative'),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('org_id', 'request_id', name='uq_token_usage_idem_org_request')
    )
    op.create_index(op.f('ix_token_usage_idempotency_created_at'), 'token_usage_idempotency', ['created_at'], unique=False)
    op.create_index(op.f('ix_token_usage_idempotency_deleted_at'), 'token_usage_idempotency', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_token_usage_idempotency_org_id'), 'token_usage_idempotency', ['org_id'], unique=False)
    op.create_index(op.f('ix_token_usage_idempotency_user_id'), 'token_usage_idempotency', ['user_id'], unique=False)
    op.create_table('ai_chat_messages',
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('token_count', sa.Integer(), nullable=True),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("role IN ('user', 'assistant', 'system', 'tool')", name='ck_ai_chat_messages_role_valid'),
    sa.CheckConstraint('token_count IS NULL OR token_count >= 0', name='ck_ai_chat_messages_token_count_non_negative'),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['session_id', 'org_id', 'user_id'], ['ai_chat_sessions.id', 'ai_chat_sessions.org_id', 'ai_chat_sessions.user_id'], name='fk_ai_chat_messages_session_org_user', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['session_id'], ['ai_chat_sessions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_chat_messages_created_at'), 'ai_chat_messages', ['created_at'], unique=False)
    op.create_index(op.f('ix_ai_chat_messages_deleted_at'), 'ai_chat_messages', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_ai_chat_messages_org_id'), 'ai_chat_messages', ['org_id'], unique=False)
    op.create_index(op.f('ix_ai_chat_messages_session_id'), 'ai_chat_messages', ['session_id'], unique=False)
    op.create_index(op.f('ix_ai_chat_messages_user_id'), 'ai_chat_messages', ['user_id'], unique=False)
    op.create_table('tables',
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('folder_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('icon', sa.String(length=50), nullable=True),
    sa.Column('color', sa.String(length=20), nullable=True),
    sa.Column('is_archived', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['folder_id'], ['table_folders.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tables_created_at'), 'tables', ['created_at'], unique=False)
    op.create_index(op.f('ix_tables_deleted_at'), 'tables', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_tables_folder_id'), 'tables', ['folder_id'], unique=False)
    op.create_index(op.f('ix_tables_org_id'), 'tables', ['org_id'], unique=False)
    op.create_table('report_widgets',
    sa.Column('dashboard_id', sa.UUID(), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), server_default=sa.text("'Новый виджет'"), nullable=False),
    sa.Column('widget_type', sa.String(length=50), server_default=sa.text("'metric'"), nullable=False),
    sa.Column('table_id', sa.UUID(), nullable=True),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('position', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['dashboard_id'], ['report_dashboards.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['table_id'], ['tables.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_report_widgets_created_at'), 'report_widgets', ['created_at'], unique=False)
    op.create_index(op.f('ix_report_widgets_dashboard_id'), 'report_widgets', ['dashboard_id'], unique=False)
    op.create_index(op.f('ix_report_widgets_deleted_at'), 'report_widgets', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_report_widgets_org_id'), 'report_widgets', ['org_id'], unique=False)
    op.create_index(op.f('ix_report_widgets_table_id'), 'report_widgets', ['table_id'], unique=False)
    op.create_table('table_columns',
    sa.Column('table_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('field_type', sa.String(length=50), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('is_required', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('is_primary', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('default_value', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['table_id'], ['tables.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_table_columns_created_at'), 'table_columns', ['created_at'], unique=False)
    op.create_index(op.f('ix_table_columns_deleted_at'), 'table_columns', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_table_columns_table_id'), 'table_columns', ['table_id'], unique=False)
    op.create_table('table_records',
    sa.Column('table_id', sa.UUID(), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('position', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['table_id'], ['tables.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_table_records_created_at'), 'table_records', ['created_at'], unique=False)
    op.create_index(op.f('ix_table_records_deleted_at'), 'table_records', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_table_records_org_id'), 'table_records', ['org_id'], unique=False)
    op.create_index(op.f('ix_table_records_table_id'), 'table_records', ['table_id'], unique=False)
    op.create_table('table_views',
    sa.Column('table_id', sa.UUID(), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('view_type', sa.String(length=50), nullable=False),
    sa.Column('filters', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('sorts', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['table_id'], ['tables.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_table_views_created_at'), 'table_views', ['created_at'], unique=False)
    op.create_index(op.f('ix_table_views_deleted_at'), 'table_views', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_table_views_org_id'), 'table_views', ['org_id'], unique=False)
    op.create_index(op.f('ix_table_views_table_id'), 'table_views', ['table_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_table_views_table_id'), table_name='table_views')
    op.drop_index(op.f('ix_table_views_org_id'), table_name='table_views')
    op.drop_index(op.f('ix_table_views_deleted_at'), table_name='table_views')
    op.drop_index(op.f('ix_table_views_created_at'), table_name='table_views')
    op.drop_table('table_views')
    op.drop_index(op.f('ix_table_records_table_id'), table_name='table_records')
    op.drop_index(op.f('ix_table_records_org_id'), table_name='table_records')
    op.drop_index(op.f('ix_table_records_deleted_at'), table_name='table_records')
    op.drop_index(op.f('ix_table_records_created_at'), table_name='table_records')
    op.drop_table('table_records')
    op.drop_index(op.f('ix_table_columns_table_id'), table_name='table_columns')
    op.drop_index(op.f('ix_table_columns_deleted_at'), table_name='table_columns')
    op.drop_index(op.f('ix_table_columns_created_at'), table_name='table_columns')
    op.drop_table('table_columns')
    op.drop_index(op.f('ix_report_widgets_table_id'), table_name='report_widgets')
    op.drop_index(op.f('ix_report_widgets_org_id'), table_name='report_widgets')
    op.drop_index(op.f('ix_report_widgets_deleted_at'), table_name='report_widgets')
    op.drop_index(op.f('ix_report_widgets_dashboard_id'), table_name='report_widgets')
    op.drop_index(op.f('ix_report_widgets_created_at'), table_name='report_widgets')
    op.drop_table('report_widgets')
    op.drop_index(op.f('ix_tables_org_id'), table_name='tables')
    op.drop_index(op.f('ix_tables_folder_id'), table_name='tables')
    op.drop_index(op.f('ix_tables_deleted_at'), table_name='tables')
    op.drop_index(op.f('ix_tables_created_at'), table_name='tables')
    op.drop_table('tables')
    op.drop_index(op.f('ix_ai_chat_messages_user_id'), table_name='ai_chat_messages')
    op.drop_index(op.f('ix_ai_chat_messages_session_id'), table_name='ai_chat_messages')
    op.drop_index(op.f('ix_ai_chat_messages_org_id'), table_name='ai_chat_messages')
    op.drop_index(op.f('ix_ai_chat_messages_deleted_at'), table_name='ai_chat_messages')
    op.drop_index(op.f('ix_ai_chat_messages_created_at'), table_name='ai_chat_messages')
    op.drop_table('ai_chat_messages')
    op.drop_index(op.f('ix_token_usage_idempotency_user_id'), table_name='token_usage_idempotency')
    op.drop_index(op.f('ix_token_usage_idempotency_org_id'), table_name='token_usage_idempotency')
    op.drop_index(op.f('ix_token_usage_idempotency_deleted_at'), table_name='token_usage_idempotency')
    op.drop_index(op.f('ix_token_usage_idempotency_created_at'), table_name='token_usage_idempotency')
    op.drop_table('token_usage_idempotency')
    op.drop_index(op.f('ix_token_purchases_payment_id'), table_name='token_purchases')
    op.drop_index(op.f('ix_token_purchases_org_id'), table_name='token_purchases')
    op.drop_index(op.f('ix_token_purchases_expires_at'), table_name='token_purchases')
    op.drop_index(op.f('ix_token_purchases_deleted_at'), table_name='token_purchases')
    op.drop_index(op.f('ix_token_purchases_created_at'), table_name='token_purchases')
    op.drop_table('token_purchases')
    op.drop_index(op.f('ix_token_ledger_user_id'), table_name='token_ledger')
    op.drop_index(op.f('ix_token_ledger_request_id'), table_name='token_ledger')
    op.drop_index(op.f('ix_token_ledger_org_id'), table_name='token_ledger')
    op.drop_index(op.f('ix_token_ledger_operation'), table_name='token_ledger')
    op.drop_index(op.f('ix_token_ledger_deleted_at'), table_name='token_ledger')
    op.drop_index(op.f('ix_token_ledger_created_at'), table_name='token_ledger')
    op.drop_table('token_ledger')
    op.drop_index(op.f('ix_token_balances_org_id'), table_name='token_balances')
    op.drop_index(op.f('ix_token_balances_deleted_at'), table_name='token_balances')
    op.drop_index(op.f('ix_token_balances_created_at'), table_name='token_balances')
    op.drop_table('token_balances')
    op.drop_index(op.f('ix_table_folders_parent_id'), table_name='table_folders')
    op.drop_index(op.f('ix_table_folders_org_id'), table_name='table_folders')
    op.drop_index(op.f('ix_table_folders_deleted_at'), table_name='table_folders')
    op.drop_index(op.f('ix_table_folders_created_at'), table_name='table_folders')
    op.drop_table('table_folders')
    op.drop_index(op.f('ix_subscriptions_deleted_at'), table_name='subscriptions')
    op.drop_index(op.f('ix_subscriptions_created_at'), table_name='subscriptions')
    op.drop_table('subscriptions')
    op.drop_index(op.f('ix_report_dashboards_org_id'), table_name='report_dashboards')
    op.drop_index(op.f('ix_report_dashboards_deleted_at'), table_name='report_dashboards')
    op.drop_index(op.f('ix_report_dashboards_created_at'), table_name='report_dashboards')
    op.drop_table('report_dashboards')
    op.drop_index(op.f('ix_refresh_tokens_user_id'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_deleted_at'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_created_at'), table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    op.drop_index(op.f('ix_org_storage_usage_org_id'), table_name='org_storage_usage')
    op.drop_index(op.f('ix_org_storage_usage_deleted_at'), table_name='org_storage_usage')
    op.drop_index(op.f('ix_org_storage_usage_created_at'), table_name='org_storage_usage')
    op.drop_table('org_storage_usage')
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_org_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_deleted_at'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_created_at'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_memberships_user_id'), table_name='memberships')
    op.drop_index(op.f('ix_memberships_org_id'), table_name='memberships')
    op.drop_index(op.f('ix_memberships_deleted_at'), table_name='memberships')
    op.drop_index(op.f('ix_memberships_created_at'), table_name='memberships')
    op.drop_table('memberships')
    op.drop_index(op.f('ix_kb_pages_parent_id'), table_name='kb_pages')
    op.drop_index(op.f('ix_kb_pages_org_id'), table_name='kb_pages')
    op.drop_index(op.f('ix_kb_pages_deleted_at'), table_name='kb_pages')
    op.drop_index(op.f('ix_kb_pages_created_at'), table_name='kb_pages')
    op.drop_table('kb_pages')
    op.drop_index(op.f('ix_invites_org_id'), table_name='invites')
    op.drop_index(op.f('ix_invites_email'), table_name='invites')
    op.drop_index(op.f('ix_invites_deleted_at'), table_name='invites')
    op.drop_index(op.f('ix_invites_created_at'), table_name='invites')
    op.drop_table('invites')
    op.execute("DROP TRIGGER IF EXISTS trg_folders_depth_update ON folders")
    op.execute("DROP TRIGGER IF EXISTS trg_folders_depth_insert ON folders")
    op.execute("DROP FUNCTION IF EXISTS crm_enforce_folders_depth()")
    op.drop_index(op.f('ix_folders_parent_id'), table_name='folders')
    op.drop_index(op.f('ix_folders_org_id'), table_name='folders')
    op.drop_index(op.f('ix_folders_deleted_at'), table_name='folders')
    op.drop_index(op.f('ix_folders_created_by'), table_name='folders')
    op.drop_index(op.f('ix_folders_created_at'), table_name='folders')
    op.drop_table('folders')
    op.drop_index(op.f('ix_events_org_id'), table_name='events')
    op.drop_index(op.f('ix_events_deleted_at'), table_name='events')
    op.drop_index(op.f('ix_events_created_at'), table_name='events')
    op.drop_table('events')
    op.drop_index(op.f('ix_docs_ai_generation_jobs_user_id'), table_name='docs_ai_generation_jobs')
    op.drop_index(op.f('ix_docs_ai_generation_jobs_org_id'), table_name='docs_ai_generation_jobs')
    op.drop_index(op.f('ix_docs_ai_generation_jobs_file_id'), table_name='docs_ai_generation_jobs')
    op.drop_index(op.f('ix_docs_ai_generation_jobs_deleted_at'), table_name='docs_ai_generation_jobs')
    op.drop_index(op.f('ix_docs_ai_generation_jobs_created_at'), table_name='docs_ai_generation_jobs')
    op.drop_table('docs_ai_generation_jobs')
    op.drop_index(op.f('ix_audit_logs_org_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_deleted_at'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_created_at'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_correlation_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_ai_user_limits_user_id'), table_name='ai_user_limits')
    op.drop_index(op.f('ix_ai_user_limits_org_id'), table_name='ai_user_limits')
    op.drop_index(op.f('ix_ai_user_limits_deleted_at'), table_name='ai_user_limits')
    op.drop_index(op.f('ix_ai_user_limits_created_at'), table_name='ai_user_limits')
    op.drop_table('ai_user_limits')
    op.drop_index(op.f('ix_ai_usage_logs_user_id'), table_name='ai_usage_logs')
    op.drop_index(op.f('ix_ai_usage_logs_org_id'), table_name='ai_usage_logs')
    op.drop_index(op.f('ix_ai_usage_logs_deleted_at'), table_name='ai_usage_logs')
    op.drop_index(op.f('ix_ai_usage_logs_created_at'), table_name='ai_usage_logs')
    op.drop_table('ai_usage_logs')
    op.drop_index(op.f('ix_ai_org_limits_org_id'), table_name='ai_org_limits')
    op.drop_index(op.f('ix_ai_org_limits_deleted_at'), table_name='ai_org_limits')
    op.drop_index(op.f('ix_ai_org_limits_created_at'), table_name='ai_org_limits')
    op.drop_table('ai_org_limits')
    op.drop_index(op.f('ix_ai_chat_sessions_user_id'), table_name='ai_chat_sessions')
    op.drop_index(op.f('ix_ai_chat_sessions_org_id'), table_name='ai_chat_sessions')
    op.drop_index(op.f('ix_ai_chat_sessions_deleted_at'), table_name='ai_chat_sessions')
    op.drop_index(op.f('ix_ai_chat_sessions_created_at'), table_name='ai_chat_sessions')
    op.drop_table('ai_chat_sessions')
    op.drop_index(op.f('ix_access_rules_user_id'), table_name='access_rules')
    op.drop_index(op.f('ix_access_rules_resource_type'), table_name='access_rules')
    op.drop_index(op.f('ix_access_rules_resource_id'), table_name='access_rules')
    op.drop_index(op.f('ix_access_rules_org_id'), table_name='access_rules')
    op.drop_index(op.f('ix_access_rules_deleted_at'), table_name='access_rules')
    op.drop_index(op.f('ix_access_rules_created_at'), table_name='access_rules')
    op.drop_table('access_rules')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_deleted_at'), table_name='users')
    op.drop_index(op.f('ix_users_created_at'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_token_packages_deleted_at'), table_name='token_packages')
    op.drop_index(op.f('ix_token_packages_created_at'), table_name='token_packages')
    op.drop_index(op.f('ix_token_packages_code'), table_name='token_packages')
    op.drop_table('token_packages')
    op.drop_index(op.f('ix_superadmin_runtime_settings_deleted_at'), table_name='superadmin_runtime_settings')
    op.drop_index(op.f('ix_superadmin_runtime_settings_created_at'), table_name='superadmin_runtime_settings')
    op.drop_table('superadmin_runtime_settings')
    op.drop_index(op.f('ix_superadmin_runtime_secrets_deleted_at'), table_name='superadmin_runtime_secrets')
    op.drop_index(op.f('ix_superadmin_runtime_secrets_created_at'), table_name='superadmin_runtime_secrets')
    op.drop_table('superadmin_runtime_secrets')
    op.drop_index(op.f('ix_superadmin_runtime_audits_deleted_at'), table_name='superadmin_runtime_audits')
    op.drop_index(op.f('ix_superadmin_runtime_audits_created_at'), table_name='superadmin_runtime_audits')
    op.drop_table('superadmin_runtime_audits')
    op.drop_index(op.f('ix_plans_deleted_at'), table_name='plans')
    op.drop_index(op.f('ix_plans_created_at'), table_name='plans')
    op.drop_table('plans')
    op.drop_index(op.f('ix_organizations_slug'), table_name='organizations')
    op.drop_index(op.f('ix_organizations_deleted_at'), table_name='organizations')
    op.drop_index(op.f('ix_organizations_created_at'), table_name='organizations')
    op.drop_table('organizations')
    op.drop_index(op.f('ix_files_type'), table_name='files')
    op.drop_index(op.f('ix_files_status'), table_name='files')
    op.drop_index(op.f('ix_files_org_id'), table_name='files')
    op.drop_index(op.f('ix_files_folder_id'), table_name='files')
    op.drop_index(op.f('ix_files_deleted_at'), table_name='files')
    op.drop_index(op.f('ix_files_current_version_id'), table_name='files')
    op.drop_index(op.f('ix_files_created_at'), table_name='files')
    op.drop_table('files')
    op.drop_index(op.f('ix_file_versions_file_id'), table_name='file_versions')
    op.drop_index(op.f('ix_file_versions_deleted_at'), table_name='file_versions')
    op.drop_index(op.f('ix_file_versions_created_by'), table_name='file_versions')
    op.drop_index(op.f('ix_file_versions_created_at'), table_name='file_versions')
    op.drop_table('file_versions')
    op.drop_index(op.f('ix_billing_runtime_settings_deleted_at'), table_name='billing_runtime_settings')
    op.drop_index(op.f('ix_billing_runtime_settings_created_at'), table_name='billing_runtime_settings')
    op.drop_table('billing_runtime_settings')
    op.drop_index(op.f('ix_billing_runtime_secrets_deleted_at'), table_name='billing_runtime_secrets')
    op.drop_index(op.f('ix_billing_runtime_secrets_created_at'), table_name='billing_runtime_secrets')
    op.drop_table('billing_runtime_secrets')
    op.drop_index(op.f('ix_billing_runtime_audits_deleted_at'), table_name='billing_runtime_audits')
    op.drop_index(op.f('ix_billing_runtime_audits_created_at'), table_name='billing_runtime_audits')
    op.drop_table('billing_runtime_audits')
    op.drop_index(op.f('ix_ai_runtime_settings_deleted_at'), table_name='ai_runtime_settings')
    op.drop_index(op.f('ix_ai_runtime_settings_created_at'), table_name='ai_runtime_settings')
    op.drop_table('ai_runtime_settings')
    op.drop_index(op.f('ix_ai_runtime_secrets_deleted_at'), table_name='ai_runtime_secrets')
    op.drop_index(op.f('ix_ai_runtime_secrets_created_at'), table_name='ai_runtime_secrets')
    op.drop_table('ai_runtime_secrets')
    op.drop_index(op.f('ix_ai_runtime_audits_deleted_at'), table_name='ai_runtime_audits')
    op.drop_index(op.f('ix_ai_runtime_audits_created_at'), table_name='ai_runtime_audits')
    op.drop_table('ai_runtime_audits')
    # ### end Alembic commands ###
