"""add_recurrence_to_events

Revision ID: dac9a1aa1a4b
Revises: cb1ce72d827c
Create Date: 2026-02-18 12:20:34.727711

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dac9a1aa1a4b'
down_revision: Union[str, None] = 'cb1ce72d827c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('recurrence', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('events', 'recurrence')
    # ### end Alembic commands ###
