from __future__ import annotations

import re

import bleach
from bleach.css_sanitizer import CSSSanitizer

ALLOWED_TAGS = frozenset(
    {
        "a",
        "abbr",
        "address",
        "article",
        "aside",
        "b",
        "blockquote",
        "br",
        "button",
        "caption",
        "code",
        "col",
        "colgroup",
        "dd",
        "del",
        "details",
        "div",
        "dl",
        "dt",
        "em",
        "figcaption",
        "figure",
        "footer",
        "h1",
        "h2",
        "h3",
        "h4",
        "h5",
        "h6",
        "header",
        "hgroup",
        "hr",
        "i",
        "img",
        "ins",
        "kbd",
        "label",
        "li",
        "main",
        "mark",
        "nav",
        "ol",
        "p",
        "picture",
        "pre",
        "s",
        "section",
        "small",
        "source",
        "span",
        # <style> is kept so pasted "pure HTML" pages render with their own CSS.
        # Safe because KB HTML renders in a fully sandboxed iframe (no allow-scripts,
        # no allow-same-origin) — CSS cannot execute code or read the parent page.
        "style",
        "strong",
        "sub",
        "summary",
        "sup",
        "table",
        "tbody",
        "td",
        "tfoot",
        "th",
        "thead",
        "time",
        "tr",
        "u",
        "ul",
        "wbr",
    }
)

ALLOWED_ATTRIBUTES = {
    "*": ["align", "class", "dir", "id", "lang", "role", "style", "title"],
    "a": ["href", "name", "rel", "target"],
    "col": ["span", "width"],
    "colgroup": ["span", "width"],
    "img": ["alt", "height", "loading", "src", "srcset", "width"],
    "ol": ["reversed", "start", "type"],
    "source": ["media", "sizes", "src", "srcset", "type", "width", "height"],
    "td": ["colspan", "headers", "rowspan"],
    "th": ["colspan", "headers", "rowspan", "scope"],
    "ul": ["type"],
}

ALLOWED_CSS_PROPERTIES = frozenset(
    {
        "align-content",
        "align-items",
        "align-self",
        "aspect-ratio",
        "background",
        "background-clip",
        "background-color",
        "background-image",
        "background-position",
        "background-repeat",
        "background-size",
        "border",
        "border-bottom",
        "border-color",
        "border-left",
        "border-radius",
        "border-right",
        "border-spacing",
        "border-style",
        "border-top",
        "border-width",
        "bottom",
        "box-shadow",
        "box-sizing",
        "caption-side",
        "color",
        "column-gap",
        "cursor",
        "display",
        "flex",
        "flex-basis",
        "flex-direction",
        "flex-flow",
        "flex-grow",
        "flex-shrink",
        "flex-wrap",
        "float",
        "font",
        "font-family",
        "font-size",
        "font-style",
        "font-weight",
        "gap",
        "grid",
        "grid-auto-columns",
        "grid-auto-flow",
        "grid-auto-rows",
        "grid-column",
        "grid-row",
        "grid-template",
        "grid-template-areas",
        "grid-template-columns",
        "grid-template-rows",
        "height",
        "inset",
        "justify-content",
        "justify-items",
        "justify-self",
        "left",
        "letter-spacing",
        "line-height",
        "list-style-position",
        "list-style-type",
        "margin",
        "margin-bottom",
        "margin-left",
        "margin-right",
        "margin-top",
        "max-height",
        "max-width",
        "min-height",
        "min-width",
        "object-fit",
        "object-position",
        "opacity",
        "order",
        "overflow",
        "overflow-x",
        "overflow-y",
        "padding",
        "padding-bottom",
        "padding-left",
        "padding-right",
        "padding-top",
        "place-content",
        "place-items",
        "position",
        "right",
        "row-gap",
        "text-align",
        "text-decoration",
        "text-overflow",
        "text-shadow",
        "text-transform",
        "top",
        "transform",
        "transition",
        "vertical-align",
        "white-space",
        "width",
        "word-break",
        "z-index",
    }
)

_CSS_SANITIZER = CSSSanitizer(allowed_css_properties=ALLOWED_CSS_PROPERTIES)
# <style> is intentionally NOT blocked here — it is kept (see ALLOWED_TAGS) so
# pure-HTML KB pages render with their own CSS inside the sandboxed iframe.
_BLOCKED_CONTAINER_RE = re.compile(
    r"<(script|iframe|object|embed|svg|math|template|form)\b[^>]*>.*?</\1\s*>",
    flags=re.IGNORECASE | re.DOTALL,
)


def sanitize_knowledge_html(html: str | None) -> str:
    """Return a safe HTML fragment for sandboxed KB page rendering."""
    without_blocked_containers = _BLOCKED_CONTAINER_RE.sub("", html or "")
    cleaned = bleach.clean(
        without_blocked_containers,
        tags=ALLOWED_TAGS,
        attributes=ALLOWED_ATTRIBUTES,
        protocols={"http", "https", "mailto", "tel"},
        strip=True,
        strip_comments=True,
        css_sanitizer=_CSS_SANITIZER,
    )
    return bleach.linkify(
        cleaned,
        callbacks=[bleach.callbacks.nofollow, bleach.callbacks.target_blank],
        skip_tags={"pre", "code"},
        parse_email=False,
    )
